// <auto-generated />
namespace CS305_WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class needed2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(needed2));
        
        string IMigrationMetadata.Id
        {
            get { return "201711271719288_needed2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
